#include <asm/asmgen.h>
// TODO: Function without return doesn't have the 'close' sequence
int ASM_generate(lir_ctx_t* lctx, sym_table_t* smt, asm_gen_t* g, FILE* output) {
    fprintf(output, "; Compiled .asm file. File generated by CordellCompiler!\n");
    g->generator(lctx, smt, output);
    return 1;
}
