/* !!! AUTOGENERATED CODE !!! */
/* See: https://github.com/j1sk1ss/NeuralIR */
#ifndef INLINE_MODEL_H
#define INLINE_MODEL_H

#ifdef __cplusplus
extern "C" {
#endif

#define INLINE_FEATURE_COUNT 12
#define INLINE_FEATURE_SITE_CALLEE_IN_SAME_FILE 0 /* 1 if caller and callee are from the same source file, else 0. */
#define INLINE_FEATURE_SITE_CALLEE_IN_SAME_DIR 1 /* 1 if caller and callee are from the same directory, else 0. */
#define INLINE_FEATURE_CALLEE_SIGNATURE_HAS_INLINE_MODIFIER 2 /* 1 if the callee declaration has an inline modifier, else 0. */
#define INLINE_FEATURE_CALLEE_AST_HAS_SIDE_EFFECTS 3 /* 1 if the callee AST contains calls, syscalls, assignments, inc/dec, or dereference side effects. */
#define INLINE_FEATURE_CALLEE_INFO_IR_COUNT 4 /* Total number of IR instructions in the callee. */
#define INLINE_FEATURE_CALLEE_INFO_FUNCCALLS 5 /* Number of function-call or syscall IR instructions in the callee. */
#define INLINE_FEATURE_CALLEE_AST_BRANCH_COUNT 6 /* Number of if/condition nodes in the callee AST. */
#define INLINE_FEATURE_CALLEE_BODY_RETURN_COUNT 7 /* Number of return statements in the callee body. */
#define INLINE_FEATURE_CALLEE_SIGNATURE_PARAM_COUNT 8 /* Number of formal parameters in the callee; void-only parameter lists count as 0. */
#define INLINE_FEATURE_CALLEE_SIGNATURE_RETURNS_VOID 9 /* 1 if the callee return type is void, else 0. */
#define INLINE_FEATURE_CALLER_CALLSITE_ARG_COUNT 10 /* Number of arguments at this callsite. */
#define INLINE_FEATURE_CALLER_INSTRUCTION_INFO_IS_DOM 11 /* 1 if the call instruction is in a join/dominated CFG context, else 0. */

extern const double INLINE_MODEL_THRESHOLD;
double inline_model_predict_proba(const double* x);
int inline_model_predict(const double* x);

#ifdef __cplusplus
}
#endif

#endif /* INLINE_MODEL_H */
